

;
; +-------------------------------------------------------------------------+
; |	This file is generated by The Interactive Disassembler (IDA)	    |
; |	Copyright (c) 2007 by DataRescue sa/nv,	<ida@datarescue.com>	    |
; |	    Licensed to: GVU, Gerhard Uphoff, 1	user, adv, 10/2007	    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	3F21BACC1E619A897E5DA5A567413AB4

; File Name   :	Z:\emu\gen\s2a\sym\left_6b5c4_mainloadblocks.bin
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 0324h Loaded length: 0324h

; Processor:	    68000
; Target Assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as	-M"

; ===========================================================================

; Segment type:	Pure code
; segment "ROM"
mapinittbl:	dc.l byte_D5DB2+$4000000 ; XREF: zone1cg
		dc.l byte_D4FB2+$5000000 ; XREF: zone1blk
off_8:		dc.l byte_DA9CE		; XREF:	zone1map
		dc.b   0,$81,  4,  4	; 0
		dc.l byte_CA3AE+$6000000 ; XREF: zone0dcg
		dc.l byte_C940E+$7000000 ; XREF: zone0dblk
		dc.l byte_CCFB2		; XREF:	zone0dmap
		dc.b   0,$82,  5,  5	; 0
		dc.l byte_CA3AE+$8000000 ; XREF: zone0dcg
		dc.l byte_C940E+$9000000 ; XREF: zone0dblk
		dc.l byte_CCFB2		; XREF:	zone0dmap
		dc.b   0,$83,  6,  6	; 0
		dc.l byte_B2174+$A000000 ; XREF: zone00cg
		dc.l byte_B11D4+$B000000 ; XREF: zone00blk
		dc.l byte_B4FAC		; XREF:	zone00map
		dc.b   0,$84,  7,  7	; 0
		dc.l byte_BE58C+$C000000 ; XREF: zone08cg
		dc.l byte_BCFAC+$D000000 ; XREF: zone08blk
		dc.l byte_C140E		; XREF:	zone08map
		dc.b   0,$85,  8,  8	; 0
		dc.l byte_CA3AE+$E000000 ; XREF: zone0dcg
		dc.l byte_C940E+$F000000 ; XREF: zone0dblk
		dc.l byte_CCFB2		; XREF:	zone0dmap
		dc.b   0,$86,  9,  9	; 0
		dc.l byte_D5DB2		; XREF:	zone1cg
		dc.l byte_D4FB2		; XREF:	zone1blk
		dc.l byte_DA9CE		; XREF:	zone1map
		dc.b   0,$86,$13,$13	; 0
divdevtbl:	dc.w ddev00-divdevtbl	; ...
		dc.w ddev01-divdevtbl
		dc.w ddev02-divdevtbl
		dc.w ddev03-divdevtbl
		dc.w ddev04-divdevtbl
		dc.w ddev05-divdevtbl
		dc.w ddev06-divdevtbl
		dc.w ddev07-divdevtbl
		dc.w ddev06-divdevtbl
		dc.w ddev07-divdevtbl
		dc.w ddev10-divdevtbl
		dc.w ddev11-divdevtbl
		dc.w ddev12-divdevtbl
		dc.w ddev13-divdevtbl
		dc.w ddev06-divdevtbl
		dc.w ddev07-divdevtbl
		dc.w ddev16-divdevtbl
		dc.w ddev17-divdevtbl
		dc.w ddev18-divdevtbl
		dc.w ddev19-divdevtbl
		dc.w ddev19-divdevtbl
		dc.w ddev21-divdevtbl
		dc.w ddev22-divdevtbl
		dc.w ddev23-divdevtbl
		dc.w ddev24-divdevtbl
		dc.w ddev25-divdevtbl
		dc.w ddev26-divdevtbl
		dc.w ddev27-divdevtbl
		dc.w ddev28-divdevtbl
		dc.w ddev29-divdevtbl
		dc.w ddev30-divdevtbl
		dc.w ddev31-divdevtbl
ddev00:		dc.w 4			; ...
		dc.l byte_A6A58		; XREF:	savecg
		dc.w $8F80
		dc.l byte_A61F2		; XREF:	scorecg
		dc.w $D940
		dc.l byte_A62FA		; XREF:	playnocg
		dc.w $FA80
		dc.l byte_A6410		; XREF:	ringcg
		dc.w $D780
		dc.l byte_A697E		; XREF:	tencg
		dc.w $9580
ddev01:		dc.w 2			; ...
		dc.l byte_A6504		; XREF:	itemcg
		dc.w $D000
		dc.l byte_9DF8E		; XREF:	bariacg
		dc.w $97C0
		dc.l byte_9E114		; XREF:	mutekicg
		dc.w $9BC0
ddev02:		dc.w 0			; ...
		dc.l byte_AF10A		; XREF:	yararecg
		dc.w $B400
ddev03:		dc.w 0			; ...
		dc.l byte_AF770		; XREF:	overcg
		dc.w $ABC0
ddev04:		dc.w 8			; ...
		dc.l byte_D5DB2		; XREF:	zone1cg
		dc.w 0
		dc.l byte_AC90E		; XREF:	fishcg
		dc.w $8E00
		dc.l byte_A692E		; XREF:	togecg
		dc.w $9400
		dc.l byte_AF902		; XREF:	jumpcg
		dc.w $9500
		dc.l byte_AFA04		; XREF:	jump2cg
		dc.w $9700
		dc.l byte_A394E		; XREF:	hashicg
		dc.w $98C0
		dc.l byte_A3834		; XREF:	burankocg
		dc.w $9A00
		dc.l byte_AD324		; XREF:	musicg
		dc.w $9C00
		dc.l byte_A3F60		; XREF:	jyamacg
		dc.w $D800
ddev05:		dc.w 0			; ...
		dc.l byte_AC90E		; XREF:	fishcg
		dc.w $8E00
ddev06:		dc.w 4			; ...
		dc.l byte_CA3AE		; XREF:	zone0dcg
		dc.w 0
		dc.l byte_CCD56		; XREF:	zone0dpccg
		dc.w $7A00
		dc.l byte_A57E4		; XREF:	kemuri0dcg
		dc.w $8000
		dc.l byte_A5904		; XREF:	dai0dcg
		dc.w $8300
		dc.l byte_A5BF0		; XREF:	nami0dcg
		dc.w $8800
ddev10:		dc.w 8			; ...
		dc.l byte_B2174		; XREF:	zone00cg
		dc.w 0
		dc.l byte_A418C		; XREF:	fire00cg
		dc.w $73C0
		dc.l byte_A43D2		; XREF:	taki00cg
		dc.w $75C0
		dc.l byte_A4626		; XREF:	hashi00cg
		dc.w $78C0
		dc.l byte_A4A6A		; XREF:	cso00cg
		dc.w $79C0
		dc.l byte_A692E		; XREF:	togecg
		dc.w $8680
		dc.l byte_A601E		; XREF:	bane45cg
		dc.w $8780
		dc.l byte_A5E38		; XREF:	banevcg
		dc.w $8B80
		dc.l byte_A5F54		; XREF:	banehcg
		dc.w $8E00
ddev11:		dc.w 2			; ...
		dc.l byte_A6EA0		; XREF:	waspcg
		dc.w $7CC0
		dc.l byte_A8EF8		; XREF:	snailcg
		dc.w $8040
		dc.l byte_A9476		; XREF:	bfishcg
		dc.w $8380
ddev12:		dc.w 7			; ...
		dc.l byte_BE58C		; XREF:	zone08cg
		dc.w 0
		dc.l byte_A4C02		; XREF:	brig08cg
		dc.w $6000
		dc.l byte_A4D7A		; XREF:	falls08cg
		dc.w $62A0
		dc.l byte_A534E		; XREF:	pltfrm08cg
		dc.w $6940
		dc.l byte_A540E		; XREF:	frntlite08cg
		dc.w $6B40
		dc.l byte_A564A		; XREF:	cork08cg
		dc.w $6F80
		dc.l byte_A50DC		; XREF:	gem08cg
		dc.w $7240
		dc.l byte_A5BF0		; XREF:	nami0dcg
		dc.w $8000
ddev13:		dc.w 1			; ...
		dc.l byte_A7AF8		; XREF:	redzcg
		dc.w $A000
		dc.l byte_A7086		; XREF:	bbatcg
		dc.w $A600
		dc.l byte_A6AFE		; XREF:	gatorcg
		dc.w $6000
		dc.l byte_A6EA0		; XREF:	waspcg
		dc.w $6580
		dc.l byte_A7086		; XREF:	bbatcg
		dc.w $6A00
		dc.l byte_A76FC		; XREF:	stegocg
		dc.w $7880
		dc.l byte_A7AF8		; XREF:	redzcg
		dc.w $A000
		dc.l byte_A7ECE		; XREF:	billfishcg
		dc.w $A600
ddev07:		dc.w 2			; ...
		dc.l byte_A692E		; XREF:	togecg
		dc.w $9400
		dc.l byte_AF902		; XREF:	jumpcg
		dc.w $9500
		dc.l byte_AFA04		; XREF:	jump2cg
		dc.w $9700
ddev16:		dc.w 0			; ...
		dc.l byte_AEAFC		; XREF:	zonecg
		dc.w $B000
ddev17:		dc.w 2			; ...
		dc.l byte_A9682		; XREF:	bossbacg
		dc.w $8C00
		dc.l byte_AAB08		; XREF:	boss00cg
		dc.w $9800
		dc.l byte_AB2F4		; XREF:	bosshcg
		dc.w $A800
		dc.l byte_A9682		; XREF:	bossbacg
		dc.w $8000
		dc.l byte_A9DBE		; XREF:	zdbcg
		dc.w $8C00
		dc.l byte_AA9A4		; XREF:	bossafbcg
		dc.w $9A00
		dc.l byte_AAA22		; XREF:	bosssmcg
		dc.w $9B00
		dc.l byte_AAB08		; XREF:	boss00cg
		dc.w $9D00
		dc.l byte_AB2F4		; XREF:	bosshcg
		dc.w $AD00
ddev18:		dc.w 2			; ...
		dc.l byte_AFAE0		; XREF:	golecg
		dc.w $D000
		dc.l byte_B00D0		; XREF:	btencg
		dc.w $96C0
		dc.l byte_AFF5C		; XREF:	ebigringcg
		dc.w $8C40
ddev19:		dc.w $10		; ...
ddev21:		dc.w 1			; ...
		dc.l byte_B08BC		; XREF:	usagicg
		dc.w $B000
		dc.l byte_B0F3E		; XREF:	fliccg
		dc.w $B240
ddev22:		dc.w 1			; ...
		dc.l byte_B0B70		; XREF:	pengcg
		dc.w $B000
		dc.l byte_B0CEC		; XREF:	azarcg
		dc.w $B240
ddev23:		dc.w 1			; ...
		dc.l byte_B1078		; XREF:	risucg
		dc.w $B000
		dc.l byte_B0CEC		; XREF:	azarcg
		dc.w $B240
ddev24:		dc.w 1			; ...
		dc.l byte_B0E08		; XREF:	fbutacg
		dc.w $B000
		dc.l byte_B0F3E		; XREF:	fliccg
		dc.w $B240
ddev25:		dc.w 1			; ...
		dc.l byte_B0E08		; XREF:	fbutacg
		dc.w $B000
		dc.l byte_B0A14		; XREF:	niwacg
		dc.w $B240
ddev26:		dc.w 1			; ...
		dc.l byte_B08BC		; XREF:	usagicg
		dc.w $B000
		dc.l byte_B0A14		; XREF:	niwacg
		dc.w $B240
ddev27:		dc.w 1			; ...
ddev28:		dc.w $D			; ...
ddev29:		dc.w 2			; ...
ddev30:		dc.w 2			; ...
ddev31:		dc.w 4			; ...
; end of 'ROM'

; ===========================================================================

; Segment type:	Regular
; segment "S2"
		ds.b $9CF8E
byte_9DF8E:	ds.b $186		; ...
byte_9E114:	ds.b $5720		; ...
byte_A3834:	ds.b $11A		; ...
byte_A394E:	ds.b $612		; ...
byte_A3F60:	ds.b $22C		; ...
byte_A418C:	ds.b $246		; ...
byte_A43D2:	ds.b $254		; ...
byte_A4626:	ds.b $444		; ...
byte_A4A6A:	ds.b $198		; ...
byte_A4C02:	ds.b $178		; ...
byte_A4D7A:	ds.b $362		; ...
byte_A50DC:	ds.b $272		; ...
byte_A534E:	ds.b $C0		; ...
byte_A540E:	ds.b $23C		; ...
byte_A564A:	ds.b $19A		; ...
byte_A57E4:	ds.b $120		; ...
byte_A5904:	ds.b $2EC		; ...
byte_A5BF0:	ds.b $248		; ...
byte_A5E38:	ds.b $11C		; ...
byte_A5F54:	ds.b $CA		; ...
byte_A601E:	ds.b $1D4		; ...
byte_A61F2:	ds.b $108		; ...
byte_A62FA:	ds.b $116		; ...
byte_A6410:	ds.b $F4		; ...
byte_A6504:	ds.b $42A		; ...
byte_A692E:	ds.b $50		; ...
byte_A697E:	ds.b $DA		; ...
byte_A6A58:	ds.b $A6		; ...
byte_A6AFE:	ds.b $3A2		; ...
byte_A6EA0:	ds.b $1E6		; ...
byte_A7086:	ds.b $676		; ...
byte_A76FC:	ds.b $3FC		; ...
byte_A7AF8:	ds.b $3D6		; ...
byte_A7ECE:	ds.b $102A		; ...
byte_A8EF8:	ds.b $57E		; ...
byte_A9476:	ds.b $20C		; ...
byte_A9682:	ds.b $73C		; ...
byte_A9DBE:	ds.b $BE6		; ...
byte_AA9A4:	ds.b $7E		; ...
byte_AAA22:	ds.b $E6		; ...
byte_AAB08:	ds.b $7EC		; ...
byte_AB2F4:	ds.b $161A		; ...
byte_AC90E:	ds.b $A16		; ...
byte_AD324:	ds.b $17D8		; ...
byte_AEAFC:	ds.b $60E		; ...
byte_AF10A:	ds.b $666		; ...
byte_AF770:	ds.b $192		; ...
byte_AF902:	ds.b $102		; ...
byte_AFA04:	ds.b $DC		; ...
byte_AFAE0:	ds.b $47C		; ...
byte_AFF5C:	ds.b $174		; ...
byte_B00D0:	ds.b $7EC		; ...
byte_B08BC:	ds.b $158		; ...
					; Nem_Bunny
byte_B0A14:	ds.b $15C		; ...
					; Nem_Chicken
byte_B0B70:	ds.b $17C		; ...
					; Nem_Penguin
byte_B0CEC:	ds.b $11C		; ...
					; Nem_Seal
byte_B0E08:	ds.b $136		; ...
					; Nem_Pig
byte_B0F3E:	ds.b $13A		; ...
					; Nem_Flicky
byte_B1078:	ds.b $15C		; ...
					; Nem_Squirrel
byte_B11D4:	ds.b $FA0		; ...
byte_B2174:	ds.b $2E38		; ...
byte_B4FAC:	ds.b $8000		; ...
byte_BCFAC:	ds.b $15E0		; ...
byte_BE58C:	ds.b $2E82		; ...
byte_C140E:	ds.b $8000		; ...
byte_C940E:	ds.b $FA0		; ...
byte_CA3AE:	ds.b $29A8		; ...
byte_CCD56:	ds.b $25C		; ...
byte_CCFB2:	ds.b $8000		; ...
byte_D4FB2:	ds.b $E00		; ...
byte_D5DB2:	ds.b $4C1C		; ...
byte_DA9CE:	ds.b $25632		; ...
; end of 'S2'


		END
