

;
; +-------------------------------------------------------------------------+
; |	This file is generated by The Interactive Disassembler (IDA)	    |
; |	Copyright (c) 2007 by DataRescue sa/nv,	<ida@datarescue.com>	    |
; |	    Licensed to: GVU, Gerhard Uphoff, 1	user, adv, 10/2007	    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	7851FC9B5A15C61EB9D76CE0DF84FE5B

; ---------------------------------------------------------------------------
; File Name   :	Z:\emu\gen\s2a\sym\copies\code_5b1fc
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 0714h Loaded length: 0714h

; Processor:	    68000
; Target Assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as	-M"

; ===========================================================================

; Segment type:	Pure code
; segment "ROM"

staff:
		moveq	#0,d0
		move.b	$24(a0),d0
		move.w	staff_move_tbl(pc,d0.w),d1
		jmp	staff_move_tbl(pc,d1.w)
; ---------------------------------------------------------------------------
staff_move_tbl:	dc.w staff_init-staff_move_tbl ; DATA XREF: ROM:staff_move_tblo
					; ROM:00000010o
		dc.w staff_move-staff_move_tbl
; ---------------------------------------------------------------------------

staff_init:				; DATA XREF: ROM:staff_move_tblo
		addq.b	#2,$24(a0)
		move.w	#$120,8(a0)
		move.w	#$F0,$A(a0) ; 'ð'
		move.l	#$1762E,4(a0)
		move.w	#$5A0,2(a0)
		bsr.w	$714		; XREF:	dualmodesub
		move.w	($FFFFFFF4).w,d0
		move.b	d0,$1A(a0)
		move.b	#0,1(a0)
		move.b	#0,$18(a0)
		cmp.b	#4,($FFFFF600).w
		bne.s	staff_move
		move.w	#$300,2(a0)
		bsr.w	$714		; XREF:	dualmodesub
		move.b	#$A,$1A(a0)
		tst.b	($FFFFFFE3).w
		beq.s	staff_move
		cmp.b	#$72,($FFFFF604).w ; 'r'
		bne.s	staff_move
		move.w	#$EEE,($FFFFFBC0).w
		move.w	#$880,($FFFFFBC2).w
		jmp	$C88E		; XREF:	frameout
; ---------------------------------------------------------------------------

staff_move:				; CODE XREF: ROM:0000004Ej
					; ROM:00000064j ...
		jmp	$C758		; XREF:	actionsub
; ---------------------------------------------------------------------------
staffpat:	dc.w staffsp00-staffpat	; DATA XREF: ROM:staffpato
					; ROM:00000088o ...
		dc.w staffsp01-staffpat
		dc.w staffsp02-staffpat
		dc.w staffsp03-staffpat
		dc.w staffsp04-staffpat
		dc.w staffsp05-staffpat
		dc.w staffsp06-staffpat
		dc.w staffsp07-staffpat
		dc.w staffsp08-staffpat
		dc.w staffsp09-staffpat
		dc.w staffsp10-staffpat
staffsp00:	dc.w $E			; DATA XREF: ROM:staffpato
		dc.w $F805,  $2E,  $17,$FF88; 0
		dc.w $F805,  $26,  $13,$FF98; 4
		dc.w $F805,  $1A,   $D,$FFA8; 8
		dc.w $F801,  $46,  $23,$FFB8; 12
		dc.w $F805,  $1E,   $F,$FFC0; 16
		dc.w $F805,  $3E,  $1F,$FFD8; 20
		dc.w $F805,   $E,    7,$FFE8; 24
		dc.w $F805,    4,    2,$FFF8; 28
		dc.w $F809,    8,    4,	   8; 32
		dc.w $F805,  $2E,  $17,	 $28; 36
		dc.w $F805,  $3E,  $1F,	 $38; 40
		dc.w $F805,    4,    2,	 $48; 44
		dc.w $F805,  $5C,  $2E,	 $58; 48
		dc.w $F805,  $5C,  $2E,	 $68; 52
staffsp01:	dc.w $10		; DATA XREF: ROM:00000088o
		dc.w $D805,    0,    0,$FF80; 0
		dc.w $D805,    4,    2,$FF90; 4
		dc.w $D809,    8,    4,$FFA0; 8
		dc.w $D805,   $E,    7,$FFB4; 12
		dc.w $D805,  $12,    9,$FFD0; 16
		dc.w $D805,  $16,   $B,$FFE0; 20
		dc.w $D805,    4,    2,$FFF0; 24
		dc.w $D805,  $1A,   $D,	   0; 28
		dc.w  $805,  $1E,   $F,$FFC8; 32
		dc.w  $805,    4,    2,$FFD8; 36
		dc.w  $805,  $22,  $11,$FFE8; 40
		dc.w  $805,  $26,  $13,$FFF8; 44
		dc.w  $805,  $16,   $B,	   8; 48
		dc.w  $805,  $2A,  $15,	 $20; 52
		dc.w  $805,    4,    2,	 $30; 56
		dc.w  $805,  $2E,  $17,	 $44; 60
staffsp02:	dc.w $A			; DATA XREF: ROM:0000008Ao
		dc.w $D805,  $12,    9,$FF80; 0
		dc.w $D805,  $22,  $11,$FF90; 4
		dc.w $D805,  $26,  $13,$FFA0; 8
		dc.w $D805,    0,    0,$FFB0; 12
		dc.w $D805,  $22,  $11,$FFC0; 16
		dc.w $D805,    4,    2,$FFD0; 20
		dc.w $D809,    8,    4,$FFE0; 24
		dc.w  $805,  $2A,  $15,$FFE8; 28
		dc.w  $805,  $32,  $19,$FFF8; 32
		dc.w  $805,  $36,  $1B,	   8; 36
staffsp03:	dc.w $18		; DATA XREF: ROM:0000008Co
		dc.w $D805,  $1E,   $F,$FF88; 0
		dc.w $D805,  $3A,  $1D,$FF98; 4
		dc.w $D805,    4,    2,$FFA8; 8
		dc.w $D805,  $22,  $11,$FFB8; 12
		dc.w $D805,    4,    2,$FFC8; 16
		dc.w $D805,  $1E,   $F,$FFD8; 20
		dc.w $D805,  $3E,  $1F,$FFE8; 24
		dc.w $D805,   $E,    7,$FFF8; 28
		dc.w $D805,  $22,  $11,	   8; 32
		dc.w $D805,  $42,  $21,	 $20; 36
		dc.w $D805,   $E,    7,	 $30; 40
		dc.w $D805,  $2E,  $17,	 $40; 44
		dc.w $D801,  $46,  $23,	 $50; 48
		dc.w $D805,    0,    0,	 $58; 52
		dc.w $D805,  $1A,   $D,	 $68; 56
		dc.w  $805,  $48,  $24,$FFC0; 60
		dc.w  $801,  $46,  $23,$FFD0; 64
		dc.w  $805,    0,    0,$FFD8; 68
		dc.w  $801,  $46,  $23,$FFE8; 72
		dc.w  $805,  $2E,  $17,$FFF0; 76
		dc.w  $805,  $16,   $B,	   0; 80
		dc.w  $805,    4,    2,	 $10; 84
		dc.w  $805,  $1A,   $D,	 $20; 88
		dc.w  $805,  $42,  $21,	 $30; 92
staffsp04:	dc.w $14		; DATA XREF: ROM:0000008Eo
		dc.w $D005,  $42,  $21,$FFA0; 0
		dc.w $D005,   $E,    7,$FFB0; 4
		dc.w $D005,  $2E,  $17,$FFC0; 8
		dc.w $D001,  $46,  $23,$FFD0; 12
		dc.w $D005,    0,    0,$FFD8; 16
		dc.w $D005,  $1A,   $D,$FFE8; 20
		dc.w	 5,  $4C,  $26,$FFE8; 24
		dc.w	 1,  $46,  $23,$FFF8; 28
		dc.w	 5,  $1A,   $D,	   4; 32
		dc.w	 5,  $2A,  $15,	 $14; 36
		dc.w	 5,    4,    2,	 $24; 40
		dc.w $2005,  $12,    9,$FFD0; 44
		dc.w $2005,  $3A,  $1D,$FFE0; 48
		dc.w $2005,   $E,    7,$FFF0; 52
		dc.w $2005,  $1A,   $D,	   0; 56
		dc.w $2001,  $46,  $23,	 $10; 60
		dc.w $2005,  $50,  $28,	 $18; 64
		dc.w $2005,  $22,  $11,	 $30; 68
		dc.w $2001,  $46,  $23,	 $40; 72
		dc.w $2005,   $E,    7,	 $48; 76
staffsp05:	dc.w $1A		; DATA XREF: ROM:00000090o
		dc.w $D805,  $2E,  $17,$FF98; 0
		dc.w $D805,  $26,  $13,$FFA8; 4
		dc.w $D805,  $32,  $19,$FFB8; 8
		dc.w $D805,  $1A,   $D,$FFC8; 12
		dc.w $D805,  $54,  $2A,$FFD8; 16
		dc.w $D805,  $12,    9,$FFF8; 20
		dc.w $D805,  $22,  $11,	   8; 24
		dc.w $D805,  $26,  $13,	 $18; 28
		dc.w $D805,  $42,  $21,	 $28; 32
		dc.w $D805,  $32,  $19,	 $38; 36
		dc.w $D805,  $1E,   $F,	 $48; 40
		dc.w $D805,   $E,    7,	 $58; 44
		dc.w  $809,    8,    4,$FF88; 48
		dc.w  $805,    4,    2,$FF9C; 52
		dc.w  $805,  $2E,  $17,$FFAC; 56
		dc.w  $805,    4,    2,$FFBC; 60
		dc.w  $805,  $3E,  $1F,$FFCC; 64
		dc.w  $805,  $26,  $13,$FFDC; 68
		dc.w  $805,  $1A,   $D,$FFF8; 72
		dc.w  $805,    4,    2,	   8; 76
		dc.w  $805,  $58,  $2C,	 $18; 80
		dc.w  $805,    4,    2,	 $28; 84
		dc.w  $809,    8,    4,	 $38; 88
		dc.w  $805,  $32,  $19,	 $4C; 92
		dc.w  $805,  $22,  $11,	 $5C; 96
		dc.w  $805,    4,    2,	 $6C; 100
staffsp06:	dc.w $17		; DATA XREF: ROM:00000092o
		dc.w $D005,  $2E,  $17,$FF98; 0
		dc.w $D005,  $26,  $13,$FFA8; 4
		dc.w $D005,  $32,  $19,$FFB8; 8
		dc.w $D005,  $1A,   $D,$FFC8; 12
		dc.w $D005,  $54,  $2A,$FFD8; 16
		dc.w $D005,  $12,    9,$FFF8; 20
		dc.w $D005,  $22,  $11,	   8; 24
		dc.w $D005,  $26,  $13,	 $18; 28
		dc.w $D005,    0,    0,	 $28; 32
		dc.w $D005,  $22,  $11,	 $38; 36
		dc.w $D005,    4,    2,	 $48; 40
		dc.w $D009,    8,    4,	 $58; 44
		dc.w	 5,  $4C,  $26,$FFD0; 48
		dc.w	 1,  $46,  $23,$FFE0; 52
		dc.w	 9,    8,    4,$FFE8; 56
		dc.w	 1,  $46,  $23,$FFFC; 60
		dc.w	 5,  $3E,  $1F,	   4; 64
		dc.w	 5,    4,    2,	 $14; 68
		dc.w $2009,    8,    4,$FFD0; 72
		dc.w $2005,    4,    2,$FFE4; 76
		dc.w $2005,  $1E,   $F,$FFF4; 80
		dc.w $2005,  $58,  $2C,	   4; 84
		dc.w $2005,  $2A,  $15,	 $14; 88
staffsp07:	dc.w $1F		; DATA XREF: ROM:00000094o
		dc.w $D805,  $2E,  $17,$FF80; 0
		dc.w $D805,  $12,    9,$FF90; 4
		dc.w $D805,   $E,    7,$FFA0; 8
		dc.w $D805,  $1E,   $F,$FFB0; 12
		dc.w $D801,  $46,  $23,$FFC0; 16
		dc.w $D805,    4,    2,$FFC8; 20
		dc.w $D805,  $16,   $B,$FFD8; 24
		dc.w $D805,  $3E,  $1F,$FFF8; 28
		dc.w $D805,  $3A,  $1D,	   8; 32
		dc.w $D805,    4,    2,	 $18; 36
		dc.w $D805,  $1A,   $D,	 $28; 40
		dc.w $D805,  $58,  $2C,	 $38; 44
		dc.w $D805,  $2E,  $17,	 $48; 48
		dc.w	 5,  $5C,  $2E,$FFB0; 52
		dc.w	 5,  $32,  $19,$FFC0; 56
		dc.w	 5,  $4C,  $26,$FFD0; 60
		dc.w	 1,  $46,  $23,$FFE0; 64
		dc.w	 5,  $26,  $13,$FFE8; 68
		dc.w	 9,    8,    4,	   0; 72
		dc.w	 1,  $46,  $23,	 $14; 76
		dc.w	 5,  $1A,   $D,	 $1C; 80
		dc.w	 5,   $E,    7,	 $2C; 84
		dc.w	 5,    0,    0,	 $3C; 88
		dc.w	 1,  $46,  $23,	 $4C; 92
		dc.w	 5,  $2E,  $17,	 $54; 96
		dc.w	 5,  $3A,  $1D,	 $64; 100
		dc.w	 1,  $46,  $23,	 $74; 104
		dc.w $2005,  $12,    9,$FFF8; 108
		dc.w $2005,    4,    2,	   8; 112
		dc.w $2005,  $12,    9,	 $18; 116
		dc.w $2005,    4,    2,	 $28; 120
staffsp08:	dc.w $F			; DATA XREF: ROM:00000096o
		dc.w $F805,  $12,    9,$FF80; 0
		dc.w $F805,  $22,  $11,$FF90; 4
		dc.w $F805,   $E,    7,$FFA0; 8
		dc.w $F805,  $2E,  $17,$FFB0; 12
		dc.w $F805,   $E,    7,$FFC0; 16
		dc.w $F805,  $1A,   $D,$FFD0; 20
		dc.w $F805,  $3E,  $1F,$FFE0; 24
		dc.w $F805,   $E,    7,$FFF0; 28
		dc.w $F805,  $42,  $21,	   0; 32
		dc.w $F805,  $48,  $24,	 $18; 36
		dc.w $F805,  $2A,  $15,	 $28; 40
		dc.w $F805,  $2E,  $17,	 $40; 44
		dc.w $F805,   $E,    7,	 $50; 48
		dc.w $F805,    0,    0,	 $60; 52
		dc.w $F805,    4,    2,	 $70; 56
staffsp09:	dc.w 8			; DATA XREF: ROM:00000098o
		dc.w $3005,  $3E,  $1F,$FFC0; 0
		dc.w $3005,  $22,  $11,$FFD0; 4
		dc.w $3005,  $2A,  $15,$FFE0; 8
		dc.w $3005,    4,    2,$FFF8; 12
		dc.w $3005,    0,    0,	   8; 16
		dc.w $3005,    4,    2,	 $18; 20
		dc.w $3001,  $46,  $23,	 $28; 24
		dc.w $3005,  $1A,   $D,	 $30; 28
staffsp10:	dc.w $11		; DATA XREF: ROM:0000009Ao
		dc.w $E805,  $2E,  $17,$FFB4; 0
		dc.w $E805,  $26,  $13,$FFC4; 4
		dc.w $E805,  $1A,   $D,$FFD4; 8
		dc.w $E801,  $46,  $23,$FFE4; 12
		dc.w $E805,  $1E,   $F,$FFEC; 16
		dc.w $E805,  $3E,  $1F,	   4; 20
		dc.w $E805,   $E,    7,	 $14; 24
		dc.w $E805,    4,    2,	 $24; 28
		dc.w $E809,    8,    4,	 $34; 32
		dc.w	 5,  $12,    9,$FFC0; 36
		dc.w	 5,  $22,  $11,$FFD0; 40
		dc.w	 5,   $E,    7,$FFE0; 44
		dc.w	 5,  $2E,  $17,$FFF0; 48
		dc.w	 5,   $E,    7,	   0; 52
		dc.w	 5,  $1A,   $D,	 $10; 56
		dc.w	 5,  $3E,  $1F,	 $20; 60
		dc.w	 5,  $2E,  $17,	 $30; 64
; ---------------------------------------------------------------------------
		nop
; end of 'ROM'


		END
