

;
; +-------------------------------------------------------------------------+
; |	This file is generated by The Interactive Disassembler (IDA)	    |
; |	Copyright (c) 2007 by DataRescue sa/nv,	<ida@datarescue.com>	    |
; |	    Licensed to: GVU, Gerhard Uphoff, 1	user, adv, 10/2007	    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	3EDFDF48EF52817B24548DBB26CEB5AC

; ---------------------------------------------------------------------------
; File Name   :	Z:\emu\gen\s2a\sym\copies\code_57ff8
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 02E8h Loaded length: 02E8h

; Processor:	    68000
; Target Assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as	-M"

; ===========================================================================

; Segment type:	Pure code
; segment "ROM"

oct:
		moveq	#0,d0
		move.b	$24(a0),d0
		move.w	oct_move_tbl(pc,d0.w),d1
		jmp	oct_move_tbl(pc,d1.w)
; ---------------------------------------------------------------------------
oct_move_tbl:	dc.w octinit-oct_move_tbl ; DATA XREF: ROM:oct_move_tblo
					; ROM:00000010o ...
		dc.w octmove-oct_move_tbl
		dc.w octeye-oct_move_tbl
		dc.w octshot-oct_move_tbl
; ---------------------------------------------------------------------------

octshot:				; DATA XREF: ROM:00000014o
		sub.w	#1,$2C(a0)
		bmi.s	_cnt$pdba
		rts
; ---------------------------------------------------------------------------

_cnt$pdba:				; CODE XREF: ROM:0000001Cj
		bsr.w	$2A8		; XREF:	speedset
		lea	($15CBA).l,a1
		bsr.w	$2A2		; XREF:	patchg
		bra.w	$29C		; XREF:	frameoutchk
; ---------------------------------------------------------------------------

octeye:					; DATA XREF: ROM:00000012o
		subq.w	#1,$2C(a0)
		beq.w	$296		; XREF:	frameout
		bra.w	word_290	; XREF:	actionsub
; ---------------------------------------------------------------------------

octinit:				; DATA XREF: ROM:oct_move_tblo
		move.l	#$15CCC,4(a0)
		move.w	#$238A,2(a0)
		or.b	#4,1(a0)
		move.b	#$A,$20(a0)
		move.b	#4,$18(a0)
		move.b	#$10,$19(a0)
		move.b	#$10,$16(a0)
		move.b	#8,$17(a0)
		bsr.w	$2A8		; XREF:	speedset
		jsr	$128C6		; XREF:	emycol_d
		tst.w	d1
		bpl.s	_end$rdba
		add.w	d1,$C(a0)
		move.w	#0,$12(a0)
		addq.b	#2,$24(a0)
		move.w	8(a0),d0
		sub.w	($FFFFB008).w,d0
		bpl.s	_end$rdba
		bchg	#0,$22(a0)

_end$rdba:				; CODE XREF: ROM:0000007Cj
					; ROM:00000094j
		move.w	$C(a0),$2A(a0)
		rts
; ---------------------------------------------------------------------------

octmove:				; DATA XREF: ROM:00000010o
		moveq	#0,d0
		move.b	$25(a0),d0
		move.w	octmove_tbl(pc,d0.w),d1
		jsr	octmove_tbl(pc,d1.w)
		lea	($15CBA).l,a1
		bsr.w	$2A2		; XREF:	patchg
		bra.w	$29C		; XREF:	frameoutchk
; ---------------------------------------------------------------------------
octmove_tbl:	dc.w octstand-octmove_tbl ; DATA XREF: ROM:octmove_tblo
					; ROM:000000C2o ...
		dc.w octfly-octmove_tbl
		dc.w octshoot-octmove_tbl
		dc.w octleave-octmove_tbl
; ---------------------------------------------------------------------------

octstand:				; DATA XREF: ROM:octmove_tblo
		move.w	8(a0),d0
		sub.w	($FFFFB008).w,d0
		cmp.w	#$80,d0	; '€'
		bgt.s	_done$udba
		cmp.w	#$FF80,d0
		blt.s	_done$udba
		addq.b	#2,$25(a0)
		move.b	#1,$1C(a0)

_done$udba:				; CODE XREF: ROM:000000D4j
					; ROM:000000DAj
		rts
; ---------------------------------------------------------------------------

octfly:					; DATA XREF: ROM:000000C2o
		sub.l	#$18000,$C(a0)
		move.w	$2A(a0),d0
		sub.w	$C(a0),d0
		cmp.w	#$20,d0	; ' '
		ble.s	_end$vdba
		addq.b	#2,$25(a0)
		move.w	#0,$2C(a0)

_end$vdba:				; CODE XREF: ROM:000000FCj
		rts
; ---------------------------------------------------------------------------

octshoot:				; DATA XREF: ROM:000000C4o
		sub.w	#1,$2C(a0)
		beq.w	_out$wdba
		bpl.w	_end$wdba
		move.w	#$1E,$2C(a0)
		jsr	$DAA2		; XREF:	actwkchk
		bne.s	_end0$wdba
		move.b	#$4A,0(a1) ; 'J'
		move.b	#4,$24(a1)
		move.l	#$15CCC,4(a1)
		move.b	#4,$1A(a1)
		move.w	#$24C6,2(a1)
		move.b	#3,$18(a1)
		move.b	#$10,$19(a1)
		move.w	8(a0),8(a1)
		move.w	$C(a0),$C(a1)
		move.w	#$1E,$2C(a1)
		move.b	1(a0),1(a1)
		move.b	$22(a0),$22(a1)

_end0$wdba:				; CODE XREF: ROM:00000124j
		jsr	$DAA2		; XREF:	actwkchk
		bne.s	_end$wdba
		move.b	#$4A,0(a1) ; 'J'
		move.b	#6,$24(a1)
		move.l	#$15CCC,4(a1)
		move.w	#$24C6,2(a1)
		move.b	#4,$18(a1)
		move.b	#$10,$19(a1)
		move.w	8(a0),8(a1)
		move.w	$C(a0),$C(a1)
		move.w	#$F,$2C(a1)
		move.b	1(a0),1(a1)
		move.b	$22(a0),$22(a1)
		move.b	#2,$1C(a1)
		move.w	#$FA80,$10(a1)
		btst	#0,1(a1)
		beq.s	_end$wdba
		neg.w	$10(a1)

_end$wdba:				; CODE XREF: ROM:00000114j
					; ROM:00000176j ...
		rts
; ---------------------------------------------------------------------------

_out$wdba:				; CODE XREF: ROM:00000110j
		addq.b	#2,$25(a0)
		rts
; ---------------------------------------------------------------------------

octleave:				; DATA XREF: ROM:000000C6o
		move.w	#$FFFA,d0
		btst	#0,1(a0)
		beq.s	_cnt$xdba
		neg.w	d0

_cnt$xdba:				; CODE XREF: ROM:000001E6j
		add.w	d0,8(a0)
		bra.w	$29C		; XREF:	frameoutchk
; ---------------------------------------------------------------------------
octchg:		dc.w octchg00-octchg	; DATA XREF: ROM:octchgo ROM:000001F4o ...
		dc.w octchg01-octchg
		dc.w octchg02-octchg
octchg00:	dc.b  $F,  0,$FF	; 0 ; DATA XREF: ROM:octchgo
octchg01:	dc.b   3,  1,  2,  3	; 0 ; DATA XREF: ROM:000001F4o
		dc.b $FF		; 4
octchg02:	dc.b   2,  5,  6,$FF	; 0 ; DATA XREF: ROM:000001F6o
octpat:		dc.w octsp00-octpat	; DATA XREF: ROM:octpato ROM:00000206o ...
		dc.w octsp01-octpat
		dc.w octsp02-octpat
		dc.w octsp03-octpat
		dc.w octsp04-octpat
		dc.w octsp05-octpat
		dc.w octsp06-octpat
octsp00:	dc.w 2			; DATA XREF: ROM:octpato
		dc.w $F00D,    0,    0,$FFF0; 0
		dc.w	$D,    8,    4,$FFF0; 4
octsp01:	dc.w 3			; DATA XREF: ROM:00000206o
		dc.w $F00D,    0,    0,$FFF0; 0
		dc.w	 9,  $10,    8,$FFE8; 4
		dc.w	 9,  $16,   $B,	   0; 8
octsp02:	dc.w 3			; DATA XREF: ROM:00000208o
		dc.w $F00D,    0,    0,$FFF0; 0
		dc.w	 9,  $1C,   $E,$FFE8; 4
		dc.w	 9,  $22,  $11,	   0; 8
octsp03:	dc.w 3			; DATA XREF: ROM:0000020Ao
		dc.w $F00D,    0,    0,$FFF0; 0
		dc.w	 9,  $28,  $14,$FFE8; 4
		dc.w	 9,  $2E,  $17,	   0; 8
octsp04:	dc.w 1			; DATA XREF: ROM:0000020Co
		dc.w $F001,  $34,  $1A,$FFF7; 0
octsp05:	dc.w 1			; DATA XREF: ROM:0000020Eo
		dc.w $F201,  $36,  $1B,$FFF0; 0
octsp06:	dc.w 1			; DATA XREF: ROM:00000210o
		dc.w $F201,  $38,  $1C,$FFF0; 0
word_290:	dc.w 0			; CODE XREF: ROM:0000003Aj
; end of 'ROM'


		END
