

;
; +-------------------------------------------------------------------------+
; |	This file is generated by The Interactive Disassembler (IDA)	    |
; |	Copyright (c) 2007 by DataRescue sa/nv,	<ida@datarescue.com>	    |
; |	    Licensed to: GVU, Gerhard Uphoff, 1	user, adv, 10/2007	    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	78527C3AFB091FD783C3ABC55B1DF239

; ---------------------------------------------------------------------------
; File Name   :	Z:\emu\gen\s2a\sym\copies\code_56ccc
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 0338h Loaded length: 0338h

; Processor:	    68000
; Target Assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as	-M"

; ===========================================================================

; Segment type:	Pure code
; segment "ROM"

gator:
		moveq	#0,d0
		move.b	$24(a0),d0
		move.w	gator_move_tbl(pc,d0.w),d1
		jmp	gator_move_tbl(pc,d1.w)
; ---------------------------------------------------------------------------
gator_move_tbl:	dc.w gatorinit-gator_move_tbl ;	DATA XREF: ROM:gator_move_tblo
					; ROM:00000010o
		dc.w gatormove-gator_move_tbl
; ---------------------------------------------------------------------------

gatorinit:				; DATA XREF: ROM:gator_move_tblo
		move.l	#$16330,4(a0)
		move.w	#$2300,2(a0)
		or.b	#4,1(a0)
		move.b	#$A,$20(a0)
		move.b	#4,$18(a0)
		move.b	#$10,$19(a0)
		move.b	#$10,$16(a0)
		move.b	#8,$17(a0)
		bsr.w	$2EC		; XREF:	speedset
		jsr	$128C6		; XREF:	emycol_d
		tst.w	d1
		bpl.s	_end$pdba
		add.w	d1,$C(a0)
		move.w	#0,$12(a0)
		addq.b	#2,$24(a0)

_end$pdba:				; CODE XREF: ROM:00000050j
		rts
; ---------------------------------------------------------------------------

gatormove:				; DATA XREF: ROM:00000010o
		moveq	#0,d0
		move.b	$25(a0),d0
		move.w	gatormove_tbl(pc,d0.w),d1
		jsr	gatormove_tbl(pc,d1.w)
		lea	($16316).l,a1
		bsr.w	$2E6		; XREF:	patchg
		bra.w	$2E0		; XREF:	frameoutchk
; ---------------------------------------------------------------------------
gatormove_tbl:	dc.w gator_0-gatormove_tbl ; DATA XREF:	ROM:gatormove_tblo
					; ROM:00000080o
		dc.w gator_1-gatormove_tbl
; ---------------------------------------------------------------------------

gator_0:				; DATA XREF: ROM:gatormove_tblo
		subq.w	#1,$30(a0)
		bpl.s	_jump$sdba
		addq.b	#2,$25(a0)
		move.w	#$FF40,$10(a0)
		move.b	#0,$1C(a0)
		bchg	#0,$22(a0)
		bne.s	_jump$sdba
		neg.w	$10(a0)

_jump$sdba:				; CODE XREF: ROM:00000086j
					; ROM:0000009Ej
		rts
; ---------------------------------------------------------------------------

gator_1:				; DATA XREF: ROM:00000080o
		bsr.w	checksonic
		bsr.w	$2F2		; XREF:	speedset2
		jsr	$128C6		; XREF:	emycol_d
		cmp.w	#$FFF8,d1
		blt.s	_jump2$tdba
		cmp.w	#$C,d1
		bge.s	_jump2$tdba
		add.w	d1,$C(a0)

_end$tdba:
		rts
; ---------------------------------------------------------------------------

_jump2$tdba:				; CODE XREF: ROM:000000B8j
					; ROM:000000BEj
		subq.b	#2,$25(a0)
		move.w	#$3B,$30(a0) ; ';'
		move.w	#0,$10(a0)
		move.b	#1,$1C(a0)
		rts

; =============== S U B	R O U T	I N E =======================================


checksonic:				; CODE XREF: ROM:gator_1p
		move.w	8(a0),d0
		sub.w	($FFFFB008).w,d0
		bmi.s	_rt$udba

_lft$udba:
		cmp.w	#$40,d0	; '@'
		bgt.s	_out$udba
		btst	#0,$22(a0)
		beq.s	_set$udba
		rts
; ---------------------------------------------------------------------------

_rt$udba:				; CODE XREF: checksonic+8j
		cmp.w	#$FFC0,d0
		blt.s	_out$udba
		btst	#0,$22(a0)
		beq.s	_out$udba

_set$udba:				; CODE XREF: checksonic+16j
		move.b	#2,$1C(a0)
		rts
; ---------------------------------------------------------------------------

_out$udba:				; CODE XREF: checksonic+Ej
					; checksonic+1Ej ...
		move.b	#0,$1C(a0)
		rts
; End of function checksonic

; ---------------------------------------------------------------------------
gatorchg:	dc.w gatorchg00-gatorchg ; DATA	XREF: ROM:gatorchgo
					; ROM:00000118o ...
		dc.w gatorchg01-gatorchg
		dc.w gatorchg02-gatorchg
gatorchg00:	dc.b   3,  0,  4,  2	; 0 ; DATA XREF: ROM:gatorchgo
		dc.b   3,  1,  5,$FF	; 4
gatorchg01:	dc.b  $F,  0,$FF	; 0 ; DATA XREF: ROM:00000118o
gatorchg02:	dc.b   3,  6, $A,  8	; 0 ; DATA XREF: ROM:0000011Ao
		dc.b   9,  7, $B,$FF	; 4
		dc.b   0		; 8
gatorpat:	dc.w gatorsp00-gatorpat	; DATA XREF: ROM:gatorpato
					; ROM:00000132o ...
		dc.w gatorsp01-gatorpat
		dc.w gatorsp02-gatorpat
		dc.w gatorsp03-gatorpat
		dc.w gatorsp04-gatorpat
		dc.w gatorsp05-gatorpat
		dc.w gatorsp06-gatorpat
		dc.w gatorsp07-gatorpat
		dc.w gatorsp08-gatorpat
		dc.w gatorsp09-gatorpat
		dc.w gatorsp10-gatorpat
		dc.w gatorsp11-gatorpat
gatorsp00:	dc.w 4			; DATA XREF: ROM:gatorpato
		dc.w $F80E,    0,    0,$FFE4; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1C,   $E,	   4; 8
		dc.w	 5,  $20,  $10,	  $C; 12
gatorsp01:	dc.w 4			; DATA XREF: ROM:00000132o
		dc.w $F80E,    0,    0,$FFE4; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1C,   $E,	   4; 8
		dc.w	 5,  $24,  $12,	  $C; 12
gatorsp02:	dc.w 4			; DATA XREF: ROM:00000134o
		dc.w $F80E,    0,    0,$FFE4; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1C,   $E,	   4; 8
		dc.w	 5,  $28,  $14,	  $C; 12
gatorsp03:	dc.w 4			; DATA XREF: ROM:00000136o
		dc.w $F80E,    0,    0,$FFE4; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1E,   $F,	   4; 8
		dc.w	 5,  $20,  $10,	  $C; 12
gatorsp04:	dc.w 4			; DATA XREF: ROM:00000138o
		dc.w $F80E,    0,    0,$FFE4; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1E,   $F,	   4; 8
		dc.w	 5,  $24,  $12,	  $C; 12
gatorsp05:	dc.w 4			; DATA XREF: ROM:0000013Ao
		dc.w $F80E,    0,    0,$FFE4; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1E,   $F,	   4; 8
		dc.w	 5,  $28,  $14,	  $C; 12
gatorsp06:	dc.w 4			; DATA XREF: ROM:0000013Co
		dc.w $F00B,   $C,    6,$FFEC; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1C,   $E,	   4; 8
		dc.w	 5,  $20,  $10,	  $C; 12
gatorsp07:	dc.w 4			; DATA XREF: ROM:0000013Eo
		dc.w $F00B,   $C,    6,$FFEC; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1C,   $E,	   4; 8
		dc.w	 5,  $24,  $12,	  $C; 12
gatorsp08:	dc.w 4			; DATA XREF: ROM:00000140o
		dc.w $F00B,   $C,    6,$FFEC; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1C,   $E,	   4; 8
		dc.w	 5,  $28,  $14,	  $C; 12
gatorsp09:	dc.w 4			; DATA XREF: ROM:00000142o
		dc.w $F00B,   $C,    6,$FFEC; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1E,   $F,	   4; 8
		dc.w	 5,  $20,  $10,	  $C; 12
gatorsp10:	dc.w 4			; DATA XREF: ROM:00000144o
		dc.w $F00B,   $C,    6,$FFEC; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1E,   $F,	   4; 8
		dc.w	 5,  $24,  $12,	  $C; 12
gatorsp11:	dc.w 4			; DATA XREF: ROM:00000146o
		dc.w $F00B,   $C,    6,$FFEC; 0
		dc.w $F805,  $18,   $C,	   4; 4
		dc.w	 1,  $1E,   $F,	   4; 8
		dc.w	 5,  $28,  $14,	  $C; 12
; end of 'ROM'


		END
